In [1]:
!pip install pyyaml

Collecting pyyaml
  Using cached pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Using cached pyyaml-6.0.3-cp314-cp314-win_amd64.whl (156 kB)
Installing collected packages: pyyaml
Successfully installed pyyaml-6.0.3

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install pandas numpy streamlit

Collecting pandas
  Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting streamlit
  Downloading streamlit-1.53.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\nithyanantham\mini_projects\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Using cached altair-6.0.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<7,>=5.5 (from streamlit)
  Downloading cachetools-6.2.6-py3-none-any.whl.metadata (5.6 kB)
Collecting click<9,>=7.0 (from streamlit)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: packaging>=20 in c:\nithyanantham\mini_projects\venv\lib\site-packages (from streamlit) (26.0)
Collecting pandas
  Using cached pandas-2.3.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting pillow<13,>=7.1.0 (from streamlit)
  Using cached pillow-12.1.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting protobuf<7,>=3.20 (from streamlit)
  Downloading protobuf-6.33.4-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-23.0.0-cp314-cp314-win_amd64.whl.metadata (3.1 kB)
Collecting requests<3,>=2.27 (from streamlit)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Using cached tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Collecting typing-extensions<5,>=4.10.0 (from streamlit)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Using cached gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Using cached pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\nithyanantham\mini_projects\venv\lib\site-packages (from streamlit) (6.5.4)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting jinja2 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting narwhals>=1.27.1 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached narwhals-2.15.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: colorama in c:\nithyanantham\mini_projects\venv\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.27->streamlit)
  Using cached charset_normalizer-3.4.4-cp314-cp314-win_amd64.whl.metadata (38 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.27->streamlit)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2.27->streamlit)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2.27->streamlit)
  Using cached certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Collecting MarkupSafe>=2.0 (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached markupsafe-3.0.3-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Using cached rpds_py-0.30.0-cp314-cp314-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: six>=1.5 in c:\nithyanantham\mini_projects\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading numpy-2.4.1-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.4 MB 8.7 MB/s eta 0:00:02
   ----------- ---------------------------- 3.7/12.4 MB 10.8 MB/s eta 0:00:01
   ------------------- -------------------- 6.0/12.4 MB 11.4 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.4 MB 11.7 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.4 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 11.4 MB/s  0:00:01
Downloading streamlit-1.53.1-py3-none-any.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   ----------- ---------------------------- 2.6/9.1 MB 11.5 MB/s eta 0:00:01
   ----------------------- ---------------- 5.2/9.1 MB 11.8 MB/s eta 0:00:01
   ---------------------------------- ----- 7.9/9.1 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 9.1/9.1 MB 11.6 MB/s  0:00:00
Using cached pandas-2.3.3-cp314-cp314-win_amd64.whl (11.1 MB)
Using cached altair-6.0.0-py3-none-any.whl (795 kB)
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-6.2.6-py3-none-any.whl (11 kB)
Using cached click-8.3.1-py3-none-any.whl (108 kB)
Using cached gitpython-3.1.46-py3-none-any.whl (208 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Using cached pillow-12.1.0-cp314-cp314-win_amd64.whl (7.2 MB)
Downloading protobuf-6.33.4-cp310-abi3-win_amd64.whl (436 kB)
Using cached pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.4-cp314-cp314-win_amd64.whl (107 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached smmap-5.0.2-py3-none-any.whl (24 kB)
Using cached tenacity-9.1.2-py3-none-any.whl (28 kB)
Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Using cached certifi-2026.1.4-py3-none-any.whl (152 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached attrs-25.4.0-py3-none-any.whl (67 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Using cached markupsafe-3.0.3-cp314-cp314-win_amd64.whl (15 kB)
Using cached narwhals-2.15.0-py3-none-any.whl (432 kB)
Downloading pyarrow-23.0.0-cp314-cp314-win_amd64.whl (28.3 MB)
   ---------------------------------------- 0.0/28.3 MB ? eta -:--:--
   --- ------------------------------------ 2.4/28.3 MB 12.5 MB/s eta 0:00:03
   ------- -------------------------------- 5.0/28.3 MB 12.4 MB/s eta 0:00:02
   ---------- ----------------------------- 7.6/28.3 MB 12.4 MB/s eta 0:00:02
   -------------- ------------------------- 10.2/28.3 MB 12.4 MB/s eta 0:00:02
   ------------------ --------------------- 13.1/28.3 MB 12.2 MB/s eta 0:00:02
   ---------------------- ----------------- 15.7/28.3 MB 12.3 MB/s eta 0:00:02
   -------------------------- ------------- 18.6/28.3 MB 12.4 MB/s eta 0:00:01
   ----------------------------- ---------- 21.0/28.3 MB 12.3 MB/s eta 0:00:01
   --------------------------------- ------ 23.3/28.3 MB 12.4 MB/s eta 0:00:01
   ------------------------------------ --- 26.0/28.3 MB 12.3 MB/s eta 0:00:01
   ---------------------------------------  28.0/28.3 MB 12.2 MB/s eta 0:00:01
   ---------------------------------------- 28.3/28.3 MB 11.5 MB/s  0:00:02
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Using cached rpds_py-0.30.0-cp314-cp314-win_amd64.whl (228 kB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: pytz, watchdog, urllib3, tzdata, typing-extensions, toml, tenacity, smmap, rpds-py, pyarrow, protobuf, pillow, numpy, narwhals, MarkupSafe, idna, click, charset_normalizer, certifi, cachetools, blinker, attrs, requests, referencing, pandas, jinja2, gitdb, pydeck, jsonschema-specifications, gitpython, jsonschema, altair, streamlit

   ----------------------------------------  0/33 [pytz]
   - --------------------------------------  1/33 [watchdog]
   - --------------------------------------  1/33 [watchdog]
   -- -------------------------------------  2/33 [urllib3]
   -- -------------------------------------  2/33 [urllib3]
   -- -------------------------------------  2/33 [urllib3]
   --- ------------------------------------  3/33 [tzdata]
   --- ------------------------------------  3/33 [tzdata]
   ------ ---------------------------------  5/33 [toml]
   -------- -------------------------------  7/33 [smmap]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ---------- -----------------------------  9/33 [pyarrow]
   ------------ --------------------------- 10/33 [protobuf]
   ------------ --------------------------- 10/33 [protobuf]
   ------------ --------------------------- 10/33 [protobuf]
   ------------ --------------------------- 10/33 [protobuf]
   ------------ --------------------------- 10/33 [protobuf]
   ------------- -------------------------- 11/33 [pillow]
   ------------- -------------------------- 11/33 [pillow]
   ------------- -------------------------- 11/33 [pillow]
   ------------- -------------------------- 11/33 [pillow]
   ------------- -------------------------- 11/33 [pillow]
   ------------- -------------------------- 11/33 [pillow]
   ------------- -------------------------- 11/33 [pillow]
   ------------- -------------------------- 11/33 [pillow]
   ------------- -------------------------- 11/33 [pillow]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   -------------- ------------------------- 12/33 [numpy]
   --------------- ------------------------ 13/33 [narwhals]
   --------------- ------------------------ 13/33 [narwhals]
   --------------- ------------------------ 13/33 [narwhals]
   --------------- ------------------------ 13/33 [narwhals]
   --------------- ------------------------ 13/33 [narwhals]
   --------------- ------------------------ 13/33 [narwhals]
   --------------- ------------------------ 13/33 [narwhals]
   --------------- ------------------------ 13/33 [narwhals]
   --------------- ------------------------ 13/33 [narwhals]
   --------------- ------------------------ 13/33 [narwhals]
   --------------- ------------------------ 13/33 [narwhals]
   ------------------ --------------------- 15/33 [idna]
   ------------------- -------------------- 16/33 [click]
   -------------------- ------------------- 17/33 [charset_normalizer]
   -------------------- ------------------- 17/33 [charset_normalizer]
   ------------------------ --------------- 20/33 [blinker]
   ------------------------- -------------- 21/33 [attrs]
   -------------------------- ------------- 22/33 [requests]
   --------------------------- ------------ 23/33 [referencing]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]
   ----------------------------- ---------- 24/33 [pandas]

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [66]:
import pandas as pd
import os
import yaml
import numpy as np

In [ ]:
# Data Extraction and Transformation: 
# ● Data is provided in YAML format, organized by months. 
# ● Within each month's folder, there are date-wise data entries. 
# ● The task is to extract this data from the YAML file and transform it into a CSV 
# format, organized by symbols  
# ● This will result in 50 CSV files after the extraction process, one for each symbol 
# or data category

In [ ]:
root_folder = r'C:\Nithyanantham\Mini_Projects\data'
output_dir = r'C:\Nithyanantham\Mini_Projects\extractdata'
date_folders=os.listdir(root_folder)
all_datas=[]
try:
    for i in date_folders:
        file_folders=os.listdir(os.path.join(root_folder,i))
        for j in file_folders:
            with open(os.path.join(root_folder, i,j), "r") as file:
                data = yaml.safe_load(file)
                all_datas.extend(data)
    df=pd.DataFrame(all_datas)
    for ticker, group in df.groupby('Ticker'):
        # with open(output_dir,'w') as file:
        file_path = os.path.join(output_dir, f"{ticker}.csv")
        group.to_csv(file_path, index=False)
except Exception as e:
    print(e)

In [ ]:
# Python DataFrame for Key Metrics: 
# ○ Market Summary: 
# ○ Top 10 Green Stocks: Sort the stocks based on their yearly return and select 
# the top 10. 
# ○ Top 10 Loss Stocks: Sort the stocks based on their yearly return and select 
# the bottom 10. 
# ■ Calculate the overall number of green vs. red stocks. 
# ■ Calculate the average price across all stocks. 
# ■ Calculate the average Volume across all stocks.

In [30]:
dfs=[]
output_dir = r'C:\Nithyanantham\Mini_Projects\extractdata'
for file in os.listdir(output_dir):
    file_path = os.path.join(output_dir, file)
    data = pd.read_csv(file_path)
    dfs.append(data)
df = pd.concat(dfs, ignore_index=True)
df.shape

(14200, 8)

In [ ]:
# ○ Top 10 Green Stocks: Sort the stocks based on their yearly return and select
# the top 10.
# ○ Top 10 Loss Stocks: Sort the stocks based on their yearly return and select
# the bottom 10.

In [ ]:
df['date']=pd.to_datetime(df['date']) # Convert Object in to Date Type

In [42]:
df['date'].dt.year

0        2023
1        2023
2        2023
3        2023
4        2023
         ...
14195    2024
14196    2024
14197    2024
14198    2024
14199    2024
Name: date, Length: 14200, dtype: int32

In [56]:
df_one=df
df_one['financial_year'] = df_one['date'].apply(
    lambda x: x.year if x.month >= 4 else x.year - 1
)
df_one=df_one.groupby(['Ticker']).agg(first_close=('close', 'first'),last_close=('close', 'last')
).reset_index()
df_one['yearly_returns'] = (
    (df_one['last_close'] - df_one['first_close'])
    / df_one['first_close']
) * 100

In [ ]:
# ○ Top 10 Green Stocks: Sort the stocks based on their yearly return and select
# the top 10.

In [133]:
top10=df_one.sort_values('yearly_returns',ascending=False,ignore_index=True).head(10)
top10.to_csv(r'C:\Nithyanantham\Mini_Projects\results\Top 10 Green Stocks.csv',index=False)

In [134]:
bottom10 = df_one.sort_values(
    'yearly_returns', ascending=True, ignore_index=True).head(10)
bottom10

bottom10.to_csv(
    r'C:\Nithyanantham\Mini_Projects\results\Bottom 10 Red Stocks.csv', index=False)

In [ ]:
df_one['Stock_Status'] = np.where(df_one['yearly_returns'] >= 0, 'Green', 'Red')
df_one

In [140]:
# ■ Calculate the overall number of green vs. red stocks.
df_one.to_csv(r'C:\Nithyanantham\Mini_Projects\results\before_ques.csv',index=False)

In [137]:
# Group by Stock_Status and count
green_red_counts = df_one.groupby(
    'Stock_Status').size().reset_index(name='Count')

# Optional: Add percentage of each status
total = green_red_counts['Count'].sum()
green_red_counts['Percentage'] = (
    green_red_counts['Count'] / total * 100).round(2)

# Export to CSV
green_red_counts.to_csv(
    r"C:\Nithyanantham\Mini_Projects\results\green_vs_red_stocks.csv",
    index=False
)

print(green_red_counts)

  Stock_Status  Count  Percentage
0        Green     45     90.0000
1          Red      5     10.0000

In [ ]:
# ■ Calculate the average price across all stocks.

In [75]:
df_one['yearly_returns'].mean()

np.float64(32.84603162115448)

In [ ]:
# ■ Calculate the average Volume across all stocks.

In [77]:
df['volume'].mean()

np.float64(6833474.649154929)

In [82]:
df.drop('financial_year', axis=1, inplace=True)

In [83]:
df

,Ticker,close,date,high,low,month,open,volume
0,ADANIENT,2387.25,2023-10-03 05:30:00,2424.90,2372.00,2023-10,2418.00,2019899
1,ADANIENT,2464.95,2023-10-04 05:30:00,2502.75,2392.25,2023-10,2402.20,2857377
2,ADANIENT,2466.35,2023-10-05 05:30:00,2486.50,2446.40,2023-10,2477.95,1132455
3,ADANIENT,2478.10,2023-10-06 05:30:00,2514.95,2466.05,2023-10,2466.35,1510035
4,ADANIENT,2442.60,2023-10-09 05:30:00,2459.70,2411.30,2023-10,2440.00,1408224
...,...,...,...,...,...,...,...,...
14195,WIPRO,566.70,2024-11-14 05:30:00,574.55,564.20,2024-11,568.95,4891760
14196,WIPRO,552.85,2024-11-18 05:30:00,566.70,540.30,2024-11,566.70,7644882
14197,WIPRO,562.00,2024-11-19 05:30:00,569.80,554.70,2024-11,556.00,6459889
14198,WIPRO,557.15,2024-11-21 05:30:00,567.60,555.30,2024-11,562.00,5836304
14199,WIPRO,571.65,2024-11-22 05:30:00,573.60,557.90,2024-11,561.95,7366616

In [85]:
df['daily_returns'] = df['close'].pct_change()
df['daily_returns_percent'] = df['close'].pct_change() * 100

In [ ]:
df = df.dropna(subset=['daily_returns'])
df

,Ticker,close,date,high,low,month,open,volume,daily_returns,daily_returns_percent
1,ADANIENT,2464.95,2023-10-04 05:30:00,2502.75,2392.25,2023-10,2402.20,2857377,0.032548,3.254791
2,ADANIENT,2466.35,2023-10-05 05:30:00,2486.50,2446.40,2023-10,2477.95,1132455,0.000568,0.056796
3,ADANIENT,2478.10,2023-10-06 05:30:00,2514.95,2466.05,2023-10,2466.35,1510035,0.004764,0.476413
4,ADANIENT,2442.60,2023-10-09 05:30:00,2459.70,2411.30,2023-10,2440.00,1408224,-0.014325,-1.432549
5,ADANIENT,2498.30,2023-10-10 05:30:00,2517.95,2443.00,2023-10,2443.00,1771910,0.022804,2.280357
...,...,...,...,...,...,...,...,...,...,...
14195,WIPRO,566.70,2024-11-14 05:30:00,574.55,564.20,2024-11,568.95,4891760,-0.004042,-0.404218
14196,WIPRO,552.85,2024-11-18 05:30:00,566.70,540.30,2024-11,566.70,7644882,-0.024440,-2.443974
14197,WIPRO,562.00,2024-11-19 05:30:00,569.80,554.70,2024-11,556.00,6459889,0.016551,1.655060
14198,WIPRO,557.15,2024-11-21 05:30:00,567.60,555.30,2024-11,562.00,5836304,-0.008630,-0.862989
14199,WIPRO,571.65,2024-11-22 05:30:00,573.60,557.90,2024-11,561.95,7366616,0.026025,2.602531

In [88]:
df['daily_returns'].mean()

np.float64(0.0047477803163692225)

In [93]:
df.groupby('Ticker')['daily_returns'].sum()

Ticker
ADANIENT       0.051582
ADANIPORTS    -0.215139
APOLLOHOSP     3.835057
ASIANPAINT    -0.768021
AXISBANK      -0.451532
BAJAJ-AUTO     4.072764
BAJAJFINSV    -0.782031
BAJFINANCE     3.837394
BEL           -0.197265
BHARTIARTL     2.849529
BPCL          -0.306104
BRITANNIA     14.826269
CIPLA         -0.490060
COALINDIA     -0.388338
DRREDDY        1.766159
EICHERMOT      2.193417
GRASIM        -0.280648
HCLTECH       -0.067353
HDFCBANK      -0.033378
HDFCLIFE      -0.524192
HEROMOTOCO     3.884372
HINDALCO      -0.538242
HINDUNILVR     2.796966
ICICIBANK     -0.285294
INDUSINDBK    -0.185770
INFY           0.748706
ITC           -0.672401
JSWSTEEL       0.898902
KOTAKBANK      0.815729
LT             0.945181
M&M            0.152054
MARUTI         2.527534
NESTLEIND     -0.769166
NTPC          -0.422201
ONGC          -0.138135
POWERGRID      0.386534
RELIANCE       2.553628
SBILIFE        0.192508
SBIN          -0.245040
SHRIRAMFIN     1.815444
SUNPHARMA     -0.126893
TATACONSUM    -0.396281
TATAMOTORS    -0.055318
TATASTEEL     -0.681873
TCS           23.823485
TECHM         -0.314787
TITAN          0.891899
TRENT          0.869898
ULTRACEMCO     0.591867
WIPRO         -0.577680
Name: daily_returns, dtype: float64

In [ ]:
# 1. Volatility Analysis:  
# ● Objective: Visualize the volatility of each stock over the past year by calculating the 
# standard deviation of daily returns. 
# ● Reason: Volatility gives insight into how much the price fluctuates, which is valuable 
# for risk assessment. Higher volatility often indicates more risk, while lower volatility 
# indicates a more stable stock. 
# Metrics: 
# ● Calculate daily returns for each stock: (Close Price - Previous Close 
# Price) / Previous Close Price. 
# ● Compute the standard deviation of daily returns for each stock to measure volatility. 
# ● Plot a bar chart showing the volatility of the top 10 most volatile stocks over the year. 
# Visualization: 
# ● Top 10 Most Volatile Stocks: A bar chart with the stock ticker on the x-axis and 
# volatility (standard deviation) on the y-axis.

In [94]:
df

,Ticker,close,date,high,low,month,open,volume,daily_returns,daily_returns_percent
1,ADANIENT,2464.95,2023-10-04 05:30:00,2502.75,2392.25,2023-10,2402.20,2857377,0.032548,3.254791
2,ADANIENT,2466.35,2023-10-05 05:30:00,2486.50,2446.40,2023-10,2477.95,1132455,0.000568,0.056796
3,ADANIENT,2478.10,2023-10-06 05:30:00,2514.95,2466.05,2023-10,2466.35,1510035,0.004764,0.476413
4,ADANIENT,2442.60,2023-10-09 05:30:00,2459.70,2411.30,2023-10,2440.00,1408224,-0.014325,-1.432549
5,ADANIENT,2498.30,2023-10-10 05:30:00,2517.95,2443.00,2023-10,2443.00,1771910,0.022804,2.280357
...,...,...,...,...,...,...,...,...,...,...
14195,WIPRO,566.70,2024-11-14 05:30:00,574.55,564.20,2024-11,568.95,4891760,-0.004042,-0.404218
14196,WIPRO,552.85,2024-11-18 05:30:00,566.70,540.30,2024-11,566.70,7644882,-0.024440,-2.443974
14197,WIPRO,562.00,2024-11-19 05:30:00,569.80,554.70,2024-11,556.00,6459889,0.016551,1.655060
14198,WIPRO,557.15,2024-11-21 05:30:00,567.60,555.30,2024-11,562.00,5836304,-0.008630,-0.862989
14199,WIPRO,571.65,2024-11-22 05:30:00,573.60,557.90,2024-11,561.95,7366616,0.026025,2.602531

In [100]:
volatility = df.groupby('Ticker')['daily_returns'].std()
volatility.sort_values(ascending=False)

Ticker
TCS           1.401027
BRITANNIA     0.873939
BAJFINANCE    0.236561
APOLLOHOSP    0.208282
BAJAJ-AUTO    0.201852
HEROMOTOCO    0.201252
HINDUNILVR    0.165760
RELIANCE      0.145390
MARUTI        0.145067
BHARTIARTL    0.136724
EICHERMOT     0.105553
DRREDDY       0.097978
SHRIRAMFIN    0.083185
BEL           0.062732
WIPRO         0.059899
BPCL          0.057403
HINDALCO      0.056937
NTPC          0.056518
TATASTEEL     0.052993
COALINDIA     0.052337
BAJAJFINSV    0.051545
TITAN         0.051169
NESTLEIND     0.048996
CIPLA         0.047786
KOTAKBANK     0.047668
LT            0.047286
ITC           0.047173
ADANIPORTS    0.045443
TECHM         0.045334
HDFCLIFE      0.040548
JSWSTEEL      0.040359
SBIN          0.039602
GRASIM        0.039377
M&M           0.039188
ICICIBANK     0.038753
AXISBANK      0.037751
SUNPHARMA     0.037546
ONGC          0.036877
ASIANPAINT    0.034589
HCLTECH       0.034262
TATACONSUM    0.034253
TRENT         0.032319
INFY          0.029615
ADANIENT      0.028601
TATAMOTORS    0.027140
POWERGRID     0.021769
ULTRACEMCO    0.020475
INDUSINDBK    0.020452
HDFCBANK      0.018196
SBILIFE       0.015137
Name: daily_returns, dtype: float64

In [142]:
annual_volatility = volatility * np.sqrt(252)
top10 = annual_volatility.sort_values(ascending=False).head(10)
top10.to_csv(r'C:\Nithyanantham\Mini_Projects\results\question1.csv',index=False)
top10

Ticker
TCS          22.2406
BRITANNIA    13.8734
BAJFINANCE    3.7553
APOLLOHOSP    3.3064
BAJAJ-AUTO    3.2043
HEROMOTOCO    3.1948
HINDUNILVR    2.6314
RELIANCE      2.3080
MARUTI        2.3029
BHARTIARTL    2.1704
Name: daily_returns, dtype: float64

In [143]:
top10_df = top10.reset_index()
top10_df.columns = ['Ticker', 'Cumulative_Return']

top10_df.to_csv(
    r'C:\Nithyanantham\Mini_Projects\results\question1.csv',
    index=False
)

In [ ]:
# 2. Cumulative Return Over Time: 
# ● Objective: Show the cumulative return of each stock from the beginning of the year to 
# the end. 
# ● Reason: The cumulative return is an important metric to visualize overall performance 
# and growth over time. This helps users compare how different stocks performed 
# relative to each other. 
# Metrics: 
# ● For each stock, calculate the cumulative return by applying a running total of daily 
# returns. 
# ● Plot a line chart for the top 5 performing stocks (based on cumulative return) over the 
# course of the year. 
# Visualization: 
# ● Cumulative Return for Top 5 Performing Stocks: A line chart displaying cumulative 
# returns for each stock over the year (increasing trend indicates positive performance).

In [106]:
df.groupby('Ticker')

In [122]:
day_zero_return=0
df['cumulative_return']=(1 + df['daily_returns']).groupby(df['Ticker']).cumprod() - 1

In [166]:
top5 = df.groupby('Ticker')['cumulative_return'].last()
top5 = top5.sort_values(ascending=False).head(5)
top5

Ticker
TCS          28.7283
BRITANNIA    15.9612
BAJAJ-AUTO    7.2998
HEROMOTOCO    5.9661
APOLLOHOSP    5.1008
Name: cumulative_return, dtype: float64

In [174]:
top5_tickers = (
    df.groupby('Ticker')['cumulative_return']
      .last()
      .sort_values(ascending=False)
      .head(5)
      .index
)

top5_tick = []

for ticker in top5_tickers:
    top5_tick.append(df[df['Ticker'] == ticker])

ans = pd.concat(top5_tick, ignore_index=True)
ans.to_csv(r'C:\Nithyanantham\Mini_Projects\results\question2.csv', index=False)

In [ ]:
# 3. Sector-wise Performance: 
# ● Objective: Provide a breakdown of stock performance by sector (sector data shared 
# as csv). 
# ● Reason: Investors and analysts often look at sector performance to gauge market 
# sentiment in specific industries (e.g., IT, Financials, Energy, etc.). 
# ● Classify each stock by its sector (this can be done by adding a separate dataset or 
# manually mapping sectors to stocks). 
# ● Calculate the average yearly return for each sector. 
# ● Plot a bar chart showing the average performance for each sector. 
# Visualization: 
# ● Average Yearly Return by Sector: A bar chart where each bar represents a sector 
# and its height indicates the average yearly return for stocks within that sector.

In [144]:
sector_df=pd.read_csv('Sector_Mapped_DF.csv')
sector_df.head()

,Ticker,close,date,high,low,month,open,volume,Daily_Return,Cumulative_return,sector
0,ADANIENT,2464.9500,10/4/2023 5:30,2502.7500,2392.2500,2023-10,2402.2000,2857377,0.0325,0.0325,MINING
1,ADANIENT,2466.3500,10/5/2023 5:30,2486.5000,2446.4000,2023-10,2477.9500,1132455,0.0006,0.0331,MINING
2,ADANIENT,2478.1000,10/6/2023 5:30,2514.9500,2466.0500,2023-10,2466.3500,1510035,0.0048,0.0381,MINING
3,ADANIENT,2442.6000,10/9/2023 5:30,2459.7000,2411.3000,2023-10,2440.0000,1408224,-0.0143,0.0232,MINING
4,ADANIENT,2498.3000,10/10/2023 5:30,2517.9500,2443.0000,2023-10,2443.0000,1771910,0.0228,0.0465,MINING

In [159]:
sector_performance = sector_df.groupby('sector')['Daily_Return'].mean()
sector_performance*100

sector
ALUMINIUM             0.1278
AUTOMOBILES           0.1605
BANKING               0.0423
CEMENT                0.1214
DEFENCE               0.2763
ENERGY                0.1243
ENGINEERING           0.0708
FINANCE               0.0440
FMCG                  0.0038
FOOD                  0.0352
FOOD & TOBACCO        0.0222
FOOD AND BEVERAGES    0.0438
INSURANCE             0.0502
MINING                0.0825
MISCELLANEOUS         0.1314
PAINTS               -0.0794
PHARMACEUTICALS       0.1021
POWER                 0.1845
RETAILING             0.2315
SOFTWARE              0.1249
STEEL                 0.0764
TELECOM               0.1961
TEXTILES              0.1186
Name: Daily_Return, dtype: float64

In [160]:
sector_performance = (
    sector_df
    .groupby('sector', as_index=False)['Daily_Return']
    .mean()
)
sector_performance

                sector  Daily_Return
0            ALUMINIUM        0.0013
1          AUTOMOBILES        0.0016
2              BANKING        0.0004
3               CEMENT        0.0012
4              DEFENCE        0.0028
5               ENERGY        0.0012
6          ENGINEERING        0.0007
7              FINANCE        0.0004
8                 FMCG        0.0000
9                 FOOD        0.0004
10      FOOD & TOBACCO        0.0002
11  FOOD AND BEVERAGES        0.0004
12           INSURANCE        0.0005
13              MINING        0.0008
14       MISCELLANEOUS        0.0013
15              PAINTS       -0.0008
16     PHARMACEUTICALS        0.0010
17               POWER        0.0018
18           RETAILING        0.0023
19            SOFTWARE        0.0012
20               STEEL        0.0008
21             TELECOM        0.0020
22            TEXTILES        0.0012

In [161]:
sector_performance.to_csv(r'C:\Nithyanantham\Mini_Projects\results\question3.csv', index=False)

In [ ]:
# 4. Stock Price Correlation: 

# Objective: Visualize the correlation between the stock prices of different companies. 
 
# ● Reason: This analysis is valuable to understand if certain stocks tend to move in 
# tandem (e.g., correlated with market trends or sector performance). 
# Metrics: 
# ● Calculate the correlation coefficient between the closing percentage of different 
# stocks. For this, use the pandas.DataFrame.corr() method. 
# ● Create a correlation matrix to identify how stocks are related to each other. 
# ● Plot a heatmap of the correlation matrix to visualize these relationships. 
# Visualization: 
# ● Stock Price Correlation Heatmap: A heatmap to show the correlation between the 
# closing prices of various stocks. Darker colors represent higher correlations.

In [179]:
returns_pivot = df.pivot(
    index='date',
    columns='Ticker',
    values='daily_returns'
)
correlation_matrix = returns_pivot.corr()
correlation_matrix.to_csv(r'C:\Nithyanantham\Mini_Projects\results\question4.csv', index=False)

In [183]:
correlation_matrix = pd.DataFrame(
    correlation_matrix.values,
    index=returns_pivot.columns,
    columns=returns_pivot.columns
)
correlation_matrix

Ticker,ADANIENT,ADANIPORTS,APOLLOHOSP,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BEL,BHARTIARTL,...,SUNPHARMA,TATACONSUM,TATAMOTORS,TATASTEEL,TCS,TECHM,TITAN,TRENT,ULTRACEMCO,WIPRO
Ticker,,,,,,,,,,,,,,,,,,,,,
ADANIENT,1.0000,0.8742,0.1365,0.2916,0.2977,0.2019,0.3565,0.3360,0.5227,0.2829,...,0.1663,0.2038,0.3241,0.4236,0.1158,0.1417,0.2833,0.1904,0.3612,0.2240
ADANIPORTS,0.8742,1.0000,-0.8120,0.8209,0.8370,-0.8071,0.8514,-0.8033,0.8861,-0.7983,...,0.8180,0.7946,0.7457,0.8620,-0.8197,0.7975,-0.7419,0.6575,-0.4270,0.8247
APOLLOHOSP,0.1365,-0.8120,1.0000,-0.9223,-0.9035,0.9952,-0.9551,0.9965,-0.9211,0.9944,...,-0.9419,-0.8972,-0.7422,-0.9311,0.9977,-0.9295,0.9637,-0.6956,0.7275,-0.9501
ASIANPAINT,0.2916,0.8209,-0.9223,1.0000,0.8667,-0.9219,0.9201,-0.9214,0.8858,-0.9208,...,0.9074,0.8782,0.7267,0.9102,-0.9302,0.8920,-0.8637,0.7111,-0.5950,0.9055
AXISBANK,0.2977,0.8370,-0.9035,0.8667,1.0000,-0.9001,0.9204,-0.8988,0.8964,-0.8963,...,0.8838,0.8464,0.7492,0.9079,-0.9102,0.8720,-0.8587,0.6976,-0.5377,0.8962
BAJAJ-AUTO,0.2019,-0.8071,0.9952,-0.9219,-0.9001,1.0000,-0.9526,0.9950,-0.9178,0.9935,...,-0.9424,-0.8917,-0.7337,-0.9271,0.9962,-0.9310,0.9624,-0.6850,0.7295,-0.9505
BAJAJFINSV,0.3565,0.8514,-0.9551,0.9201,0.9204,-0.9526,1.0000,-0.9460,0.9285,-0.9501,...,0.9321,0.9037,0.7751,0.9463,-0.9613,0.9198,-0.8998,0.7140,-0.6005,0.9446
BAJFINANCE,0.3360,-0.8033,0.9965,-0.9214,-0.8988,0.9950,-0.9460,1.0000,-0.9189,0.9947,...,-0.9451,-0.8932,-0.7423,-0.9283,0.9978,-0.9295,0.9640,-0.6889,0.7349,-0.9499
BEL,0.5227,0.8861,-0.9211,0.8858,0.8964,-0.9178,0.9285,-0.9189,1.0000,-0.9128,...,0.9014,0.8660,0.7893,0.9386,-0.9284,0.8982,-0.8758,0.7211,-0.5526,0.9162
BHARTIARTL,0.2829,-0.7983,0.9944,-0.9208,-0.8963,0.9935,-0.9501,0.9947,-0.9128,1.0000,...,-0.9369,-0.8870,-0.7321,-0.9241,0.9952,-0.9215,0.9640,-0.6804,0.7372,-0.9444
BPCL,0.4553,0.8662,-0.9168,0.8898,0.8763,-0.9127,0.9245,-0.9143,0.9296,-0.9087,...,0.9020,0.8589,0.8006,0.9283,-0.9228,0.8914,-0.8585,0.7060,-0.5538,0.9071
BRITANNIA,0.1307,-0.8192,0.9978,-0.9284,-0.9097,0.9962,-0.9609,0.9978,-0.9283,0.9951,...,-0.9491,-0.8994,-0.7523,-0.9385,0.9999,-0.9349,0.9614,-0.7011,0.7180,-0.9559
CIPLA,0.0942,0.7890,-0.9325,0.8933,0.8680,-0.9351,0.9169,-0.9366,0.8835,-0.9313,...,0.9372,0.8588,0.7237,0.8982,-0.9397,0.8859,-0.8934,0.6926,-0.6415,0.9080
COALINDIA,0.4945,0.8764,-0.9040,0.8788,0.8874,-0.9013,0.9093,-0.9031,0.9417,-0.8974,...,0.8899,0.8610,0.7968,0.9324,-0.9124,0.8798,-0.8506,0.7144,-0.5622,0.9013
DRREDDY,0.1646,-0.8020,0.9916,-0.9163,-0.8984,0.9893,-0.9451,0.9904,-0.9151,0.9892,...,-0.9266,-0.8887,-0.7306,-0.9225,0.9921,-0.9182,0.9583,-0.6805,0.7327,-0.9385
EICHERMOT,0.3316,-0.7874,0.9891,-0.9056,-0.8820,0.9882,-0.9406,0.9880,-0.9020,0.9879,...,-0.9307,-0.8803,-0.7130,-0.9118,0.9885,-0.9146,0.9613,-0.6679,0.7402,-0.9339
GRASIM,0.3445,0.8379,-0.9218,0.9121,0.9028,-0.9204,0.9385,-0.9191,0.9100,-0.9149,...,0.9089,0.8841,0.7820,0.9321,-0.9297,0.8932,-0.8570,0.7157,-0.5153,0.9162
HCLTECH,0.1399,0.7822,-0.8992,0.8641,0.8464,-0.9012,0.9050,-0.9020,0.8790,-0.8939,...,0.8841,0.8578,0.7587,0.8923,-0.9067,0.9313,-0.8510,0.6993,-0.5914,0.9402
HDFCBANK,0.3381,0.7106,-0.6655,0.6975,0.7424,-0.6582,0.7114,-0.6545,0.7154,-0.6537,...,0.6556,0.6414,0.6065,0.7284,-0.6722,0.6827,-0.6081,0.5260,-0.2956,0.6851
HDFCLIFE,0.2168,0.8162,-0.9273,0.8955,0.8870,-0.9233,0.9315,-0.9233,0.9000,-0.9206,...,0.9053,0.8749,0.7560,0.9102,-0.9325,0.8881,-0.8742,0.7063,-0.6073,0.9129
HEROMOTOCO,0.2086,-0.8081,0.9957,-0.9223,-0.9017,0.9957,-0.9533,0.9953,-0.9230,0.9932,...,-0.9412,-0.8916,-0.7352,-0.9279,0.9967,-0.9293,0.9648,-0.6863,0.7307,-0.9486
HINDALCO,0.3050,0.8368,-0.9356,0.9008,0.8875,-0.9291,0.9312,-0.9312,0.9202,-0.9245,...,0.9196,0.8741,0.7900,0.9564,-0.9386,0.9075,-0.8791,0.7246,-0.5975,0.9247
HINDUNILVR,-0.0008,-0.8181,0.9956,-0.9212,-0.9079,0.9944,-0.9566,0.9957,-0.9279,0.9936,...,-0.9464,-0.8868,-0.7472,-0.9346,0.9974,-0.9299,0.9624,-0.6953,0.7227,-0.9502
ICICIBANK,0.3946,0.8579,-0.9383,0.8980,0.9465,-0.9375,0.9456,-0.9343,0.9153,-0.9275,...,0.9179,0.8689,0.7546,0.9258,-0.9436,0.9031,-0.8943,0.6909,-0.5773,0.9245
INDUSINDBK,0.3913,-0.0704,0.3677,-0.2738,-0.1973,0.3758,-0.2388,0.3850,-0.2281,0.3801,...,-0.3066,-0.2150,-0.0671,-0.2115,0.3611,-0.3033,0.4083,-0.1204,0.4827,-0.2941
INFY,0.1151,-0.6742,0.8746,-0.7936,-0.7772,0.8691,-0.8071,0.8771,-0.7807,0.8823,...,-0.8072,-0.7355,-0.5991,-0.7891,0.8758,-0.7046,0.8677,-0.5596,0.7015,-0.7536
ITC,0.2458,0.8333,-0.9623,0.9260,0.9098,-0.9608,0.9517,-0.9602,0.9202,-0.9562,...,0.9340,0.9058,0.7603,0.9310,-0.9671,0.9248,-0.9078,0.7060,-0.6471,0.9428
JSWSTEEL,0.4057,-0.6493,0.9197,-0.8016,-0.7713,0.9186,-0.8298,0.9228,-0.7803,0.9244,...,-0.8367,-0.7836,-0.5799,-0.7481,0.9150,-0.8170,0.9148,-0.5671,0.8094,-0.8321
KOTAKBANK,0.2438,-0.7312,0.9553,-0.8689,-0.8334,0.9532,-0.8961,0.9588,-0.8573,0.9594,...,-0.8988,-0.8359,-0.6879,-0.8697,0.9549,-0.8749,0.9314,-0.6525,0.7533,-0.8920
LT,0.4831,-0.6608,0.9373,-0.8399,-0.7982,0.9356,-0.8590,0.9407,-0.7888,0.9406,...,-0.8684,-0.8163,-0.6203,-0.8174,0.9344,-0.8471,0.9204,-0.6077,0.7870,-0.8599
M&M,0.3045,0.8048,-0.8617,0.8368,0.8418,-0.8572,0.8840,-0.8613,0.8770,-0.8535,...,0.8721,0.8225,0.7861,0.8909,-0.8712,0.8539,-0.7997,0.6986,-0.4816,0.8770
MARUTI,0.3157,-0.8004,0.9945,-0.9177,-0.8964,0.9946,-0.9491,0.9951,-0.9168,0.9939,...,-0.9400,-0.8896,-0.7249,-0.9222,0.9956,-0.9266,0.9656,-0.6860,0.7360,-0.9468
NESTLEIND,0.1150,0.8061,-0.9608,0.9264,0.8911,-0.9593,0.9492,-0.9605,0.9043,-0.9595,...,0.9299,0.9136,0.7532,0.9172,-0.9666,0.9097,-0.9128,0.7031,-0.6430,0.9362
NTPC,0.5460,0.8904,-0.9323,0.9019,0.9112,-0.9293,0.9400,-0.9293,0.9496,-0.9218,...,0.9168,0.8748,0.8002,0.9449,-0.9386,0.9017,-0.8709,0.7165,-0.5648,0.9186
ONGC,0.4849,0.8346,-0.7894,0.7714,0.8050,-0.7854,0.8183,-0.7837,0.8692,-0.7736,...,0.8014,0.7662,0.7745,0.8515,-0.7973,0.7966,-0.7354,0.6508,-0.4017,0.8144
POWERGRID,0.4039,0.6744,-0.5051,0.5158,0.5747,-0.5021,0.5688,-0.5014,0.6527,-0.4876,...,0.5566,0.5218,0.5891,0.6330,-0.5158,0.5292,-0.4473,0.4848,-0.1330,0.5358
RELIANCE,0.4871,-0.7896,0.9948,-0.9167,-0.8904,0.9939,-0.9474,0.9960,-0.9078,0.9941,...,-0.9375,-0.8899,-0.7265,-0.9210,0.9958,-0.9229,0.9655,-0.6797,0.7449,-0.9427
SBILIFE,0.2892,0.0954,0.0921,0.0045,0.0012,0.0976,0.0322,0.1037,0.0019,0.1050,...,-0.0366,0.0171,0.0856,0.0030,0.0831,-0.0218,0.1386,0.0642,0.2439,-0.0064
SBIN,0.5447,0.8816,-0.8843,0.8480,0.9087,-0.8824,0.9098,-0.8778,0.9257,-0.8744,...,0.8647,0.8276,0.7800,0.9137,-0.8912,0.8655,-0.8295,0.7148,-0.5045,0.8853
SHRIRAMFIN,0.4103,-0.7222,0.9685,-0.8795,-0.8310,0.9687,-0.8954,0.9714,-0.8510,0.9701,...,-0.9002,-0.8500,-0.6655,-0.8678,0.9658,-0.8826,0.9464,-0.6349,0.7766,-0.9011
SUNPHARMA,0.1663,0.8180,-0.9419,0.9074,0.8838,-0.9424,0.9321,-0.9451,0.9014,-0.9369,...,1.0000,0.8803,0.7786,0.9203,-0.9496,0.9071,-0.8948,0.7235,-0.6299,0.9264
TATACONSUM,0.2038,0.7946,-0.8972,0.8782,0.8464,-0.8917,0.9037,-0.8932,0.8660,-0.8870,...,0.8803,1.0000,0.7331,0.8807,-0.9010,0.8765,-0.8301,0.6900,-0.5723,0.8943
TATAMOTORS,0.3241,0.7457,-0.7422,0.7267,0.7492,-0.7337,0.7751,-0.7423,0.7893,-0.7321,...,0.7786,0.7331,1.0000,0.8235,-0.7519,0.7697,-0.6745,0.6328,-0.3772,0.7805
TATASTEEL,0.4236,0.8620,-0.9311,0.9102,0.9079,-0.9271,0.9463,-0.9283,0.9386,-0.9241,...,0.9203,0.8807,0.8235,1.0000,-0.9384,0.9132,-0.8750,0.7124,-0.5596,0.9317
TCS,0.1158,-0.8197,0.9977,-0.9302,-0.9102,0.9962,-0.9613,0.9978,-0.9284,0.9952,...,-0.9496,-0.9010,-0.7519,-0.9384,1.0000,-0.9338,0.9616,-0.7007,0.7177,-0.9550
TECHM,0.1417,0.7975,-0.9295,0.8920,0.8720,-0.9310,0.9198,-0.9295,0.8982,-0.9215,...,0.9071,0.8765,0.7697,0.9132,-0.9338,1.0000,-0.8758,0.6943,-0.6037,0.9567
TITAN,0.2833,-0.7419,0.9637,-0.8637,-0.8587,0.9624,-0.8998,0.9640,-0.8758,0.9640,...,-0.8948,-0.8301,-0.6745,-0.8750,0.9616,-0.8758,1.0000,-0.6361,0.7565,-0.8988
TRENT,0.1904,0.6575,-0.6956,0.7111,0.6976,-0.6850,0.7140,-0.6889,0.7211,-0.6804,...,0.7235,0.6900,0.6328,0.7124,-0.7007,0.6943,-0.6361,1.0000,-0.3556,0.7023
ULTRACEMCO,0.3612,-0.4270,0.7275,-0.5950,-0.5377,0.7295,-0.6005,0.7349,-0.5526,0.7372,...,-0.6299,-0.5723,-0.3772,-0.5596,0.7177,-0.6037,0.7565,-0.3556,1.0000,-0.6260
WIPRO,0.2240,0.8247,-0.9501,0.9055,0.8962,-0.9505,0.9446,-0.9499,0.9162,-0.9444,...,0.9264,0.8943,0.7805,0.9317,-0.9550,0.9567,-0.8988,0.7023,-0.6260,1.0000

In [184]:
correlation_matrix.to_csv(
    r"C:\Nithyanantham\Mini_Projects\results\stock_correlation_matrix.csv"
)

In [ ]:
# 5. Top 5 Gainers and Losers (Month-wise): 
# ● Objective: Provide monthly breakdowns of the top-performing and worst-performing 
# stocks. 
# ● Reason: This analysis will allow users to observe more granular trends and 
# understand which stocks are gaining or losing momentum on a monthly basis. 
# Metrics: 
# ● Group the stock data by month and calculate the monthly return for each stock. 
# ● For each month, identify the top 5 gainers and top 5 losers based on percentage 
# change. 
# ● Create a dashboard-style visualization with 5 charts showing top gainers and losers 
# for each month (12 months total). 
# Visualization: 
# ● Top 5 Gainers and Losers by Month: Create a set of 12 bar charts for each month 
# showing the top 5 gainers and losers based on percentage return.

In [185]:
sector_df

,Ticker,close,date,high,low,month,open,volume,Daily_Return,Cumulative_return,sector
0,ADANIENT,2464.9500,10/4/2023 5:30,2502.7500,2392.2500,2023-10,2402.2000,2857377,0.0325,0.0325,MINING
1,ADANIENT,2466.3500,10/5/2023 5:30,2486.5000,2446.4000,2023-10,2477.9500,1132455,0.0006,0.0331,MINING
2,ADANIENT,2478.1000,10/6/2023 5:30,2514.9500,2466.0500,2023-10,2466.3500,1510035,0.0048,0.0381,MINING
3,ADANIENT,2442.6000,10/9/2023 5:30,2459.7000,2411.3000,2023-10,2440.0000,1408224,-0.0143,0.0232,MINING
4,ADANIENT,2498.3000,10/10/2023 5:30,2517.9500,2443.0000,2023-10,2443.0000,1771910,0.0228,0.0465,MINING
...,...,...,...,...,...,...,...,...,...,...,...
14145,WIPRO,566.7000,11/14/2024 5:30,574.5500,564.2000,2024-11,568.9500,4891760,-0.0040,0.3977,SOFTWARE
14146,WIPRO,552.8500,11/18/2024 5:30,566.7000,540.3000,2024-11,566.7000,7644882,-0.0244,0.3635,SOFTWARE
14147,WIPRO,562.0000,11/19/2024 5:30,569.8000,554.7000,2024-11,556.0000,6459889,0.0166,0.3861,SOFTWARE
14148,WIPRO,557.1500,11/21/2024 5:30,567.6000,555.3000,2024-11,562.0000,5836304,-0.0086,0.3742,SOFTWARE
14149,WIPRO,571.6500,11/22/2024 5:30,573.6000,557.9000,2024-11,561.9500,7366616,0.0260,0.4099,SOFTWARE

In [ ]:
sector_df.groupby('month')['Daily_Return']

In [188]:
monthly_returns = (
    sector_df.sort_values(['Ticker', 'date'])
      .groupby(['month', 'Ticker'])['Daily_Return']
      .apply(lambda x: (1 + x).prod() - 1)
      .reset_index(name='monthly_return')
)

In [189]:
monthly_returns

       month      Ticker  monthly_return
0    2023-10    ADANIENT         -0.0388
1    2023-10  ADANIPORTS         -0.0561
2    2023-10  APOLLOHOSP         -0.0584
3    2023-10  ASIANPAINT         -0.0540
4    2023-10    AXISBANK         -0.0569
..       ...         ...             ...
695  2024-11       TECHM          0.0863
696  2024-11       TITAN          0.0127
697  2024-11       TRENT         -0.0667
698  2024-11  ULTRACEMCO          0.0280
699  2024-11       WIPRO          0.0360

[700 rows x 3 columns]

In [190]:
top5_gainers = (
    monthly_returns
    .sort_values(['month', 'monthly_return'], ascending=[True, False])
    .groupby('month')
    .head(5)
)

In [191]:
top5_gainers

       month      Ticker  monthly_return
32   2023-10   NESTLEIND          0.0860
13   2023-10   COALINDIA          0.0766
5    2023-10  BAJAJ-AUTO          0.0593
37   2023-10     SBILIFE          0.0583
47   2023-10       TRENT          0.0464
..       ...         ...             ...
680  2024-11         M&M          0.1042
695  2024-11       TECHM          0.0863
675  2024-11        INFY          0.0825
667  2024-11     HCLTECH          0.0749
694  2024-11         TCS          0.0696

[70 rows x 3 columns]

In [192]:
top5_losers = (
    monthly_returns
    .sort_values(['month', 'monthly_return'], ascending=[True, True])
    .groupby('month')
    .head(5)
)

In [193]:
top5_losers

       month      Ticker  monthly_return
43   2023-10   TATASTEEL         -0.0723
45   2023-10       TECHM         -0.0683
38   2023-10        SBIN         -0.0620
7    2023-10  BAJFINANCE         -0.0596
2    2023-10  APOLLOHOSP         -0.0584
..       ...         ...             ...
650  2024-11    ADANIENT         -0.2440
651  2024-11  ADANIPORTS         -0.1738
653  2024-11  ASIANPAINT         -0.1579
661  2024-11   BRITANNIA         -0.1534
683  2024-11        NTPC         -0.1046

[70 rows x 3 columns]

In [194]:
top5_gainers.to_csv(
    r"C:\Nithyanantham\Mini_Projects\results\top5_gainers_monthwise.csv",
    index=False
)

top5_losers.to_csv(
    r"C:\Nithyanantham\Mini_Projects\results\top5_losers_monthwise.csv",
    index=False
)